-- ============================================================
-- RIGBASE STATION — IMPORT DATA EQUIPMENT (Fase 6)
-- Generated from data_equipment.xlsx (49 rows)
-- Tanggal generate: 2026-05-15
-- ============================================================
-- Aman dijalankan ulang berkat ON CONFLICT (tag_number) DO NOTHING.
-- Kategori & parent_unit di-lookup via subquery, jadi gak tergantung ID exact.

BEGIN;

-- DW-100A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'DW-100A',
  'Drawwork BW-100A (Cooper LTO-350)',
  (SELECT id FROM categories WHERE name = 'Drawwork' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW-100A' LIMIT 1),
  'Permanent',
  'Cooper',
  'LTO-350',
  '1407',
  1980,
  1989,
  NULL,
  'USA',
  'Steering: Vickers V20 | Engine 450 HP | Power Drawwork 350 HP | Weight Indicator: MD TOTO SN 181225004 Type/Model The Clipper',
  'Aktif',
  'Good',
  'On Rig BW-100A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  2017,
  '665/47/PLO/DMT/2019',
  '2023-10-12',
  '2027-09-15',
  NULL,
  NULL,
  2016,
  'PT Petrodrill Manufactur Indonesia',
  '63.45 Metric Ton',
  NULL,
  NULL,
  NULL,
  'Migas',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Refurbish 2016. Service: Light Workover.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- MAST-100A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'MAST-100A',
  'Mast BW-100A (Tubing Truss 29.6m)',
  (SELECT id FROM categories WHERE name = 'Mast' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW-100A' LIMIT 1),
  'Permanent',
  'Cooper',
  '97-200-6-4',
  'PD29-M140-096',
  NULL,
  NULL,
  NULL,
  NULL,
  'Tubing Truss Mast 29.6 Meter | Max Static Hook Load 63.5 Metric Ton | Crown Block: Wirerope 1"',
  'Aktif',
  'Good',
  'On Rig BW-100A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  2016,
  'PT Petrodrill Manufactur Indonesia',
  '63.45 Metric Ton',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Refurbish 2016 by PT Petrodrill.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- MOBENG-100A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'MOBENG-100A',
  'Mobile Engine BW-100A (CAT D3406)',
  (SELECT id FROM categories WHERE name = 'Mobile Engine' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW-100A' LIMIT 1),
  'Permanent',
  'Caterpillar',
  'D3406 C / DDEC S-60',
  '3ER07110 / 06RH002662',
  NULL,
  NULL,
  NULL,
  'USA',
  'Power: 450/475 HP | Transmission: Allison S6510-R / Allison S.5600 R | Trans SN: 89384 / 310105336 | Power Trans 500',
  'Aktif',
  'Good',
  'On Rig BW-100A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  2017,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'GOH 2017. Mobile Rig carrier engine.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- MP-100A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'MP-100A',
  'Mudpump BW-100A (NOV JWS-400)',
  (SELECT id FROM categories WHERE name = 'Mudpump' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW-100A' LIMIT 1),
  'Permanent',
  'National Oilwell',
  'JWS-400',
  '2638857-1',
  NULL,
  NULL,
  NULL,
  'USA',
  'Pump Type: NOV | Engine: CAT C13, SN RRA12541, 440 HP',
  'Aktif',
  'Good',
  'On Rig BW-100A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- TB-100A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'TB-100A',
  'Travelling Block BW-100A (IDEAL 330E90)',
  (SELECT id FROM categories WHERE name = 'Travelling Block' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW-100A' LIMIT 1),
  'Permanent',
  'IDEAL',
  '330E90',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '90 Ton | Wire 1 inch | Sheave 3',
  'Aktif',
  'Good',
  'On Rig BW-100A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Power Swivel Capacity 350HP. Swivel PS120 (CAT C7.1, SN G9R02287).'
)
ON CONFLICT (tag_number) DO NOTHING;

-- BOPA-100A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'BOPA-100A',
  'BOP Annular BW-100A (Hydrill GK)',
  (SELECT id FROM categories WHERE name = 'BOP Annular' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW-100A' LIMIT 1),
  'Permanent',
  'Hydril',
  'GK',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Size 7-1/16" x 3000 Psi | Type GK',
  'Aktif',
  'Good',
  'On Rig BW-100A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '005/COC-RMFR/PTFI/III/19',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- BOPR-100A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'BOPR-100A',
  'BOP Single Ram BW-100A (Shaffer)',
  (SELECT id FROM categories WHERE name = 'BOP Single Ram' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW-100A' LIMIT 1),
  'Permanent',
  'Shaffer',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Size 7-1/16" x 3000 Psi',
  'Aktif',
  'Good',
  'On Rig BW-100A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '004/COC-RMFR/PTFI/III/19',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- ACC-100A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'ACC-100A',
  'Accumulator BW-100A (Koomey)',
  (SELECT id FROM categories WHERE name = 'Accumulator' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW-100A' LIMIT 1),
  'Permanent',
  'Koomey',
  'SWA028-15SB3',
  '5695',
  1998,
  NULL,
  NULL,
  NULL,
  'Closing Unit Model SWA028-15SB3 | 2 Bottle',
  'Aktif',
  'Good',
  'On Rig BW-100A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- GS-100A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'GS-100A',
  'Genset Olympian 60Kva BW-100A',
  (SELECT id FROM categories WHERE name = 'Genset' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW-100A' LIMIT 1),
  'Permanent',
  'Olympian Perkin',
  '50-7',
  'OLY0000KLEZ00874',
  NULL,
  NULL,
  NULL,
  NULL,
  '60 kVA',
  'Aktif',
  'Good',
  'On Rig BW-100A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- TT-100A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'TT-100A',
  'Tubing Tong BW-100A (Wetco HYD RS)',
  (SELECT id FROM categories WHERE name = 'Tubing Tong' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW-100A' LIMIT 1),
  'Permanent',
  'Wetco',
  'HYD TUBING TONG RS',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Hydraulic Tubing Tong',
  'Aktif',
  'Good',
  'On Rig BW-100A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- DW-H35KD
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'DW-H35KD',
  'Drawwork BW H35KD (IDECO H-35KD)',
  (SELECT id FROM categories WHERE name = 'Drawwork' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW H35KD' LIMIT 1),
  'Permanent',
  'IDECO',
  'H-35KD BIR 3185',
  'CA-1185',
  1982,
  1983,
  NULL,
  'USA',
  'Steering: Vickers V20 | Engine 450 HP | Power Drawwork 350 HP | Weight Indicator: MD TOTCO SN 82AH0074 Type FS',
  'Aktif',
  'Good',
  'On Rig BW H35KD',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  2020,
  '784/47-26/PLO/DMT/2023',
  '2022-08-22',
  '2025-09-12',
  NULL,
  NULL,
  NULL,
  NULL,
  '71 ton',
  NULL,
  NULL,
  NULL,
  'Migas',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Mobile Rig (Workover Mobile). Service: Heavy Workover. GOH 2020.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- MAST-H35KD
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'MAST-H35KD',
  'Mast BW H35KD (Double Hidraulic)',
  (SELECT id FROM categories WHERE name = 'Mast' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW H35KD' LIMIT 1),
  'Permanent',
  'IDECO',
  'KM 96-215-GH',
  'CA-2032',
  NULL,
  NULL,
  NULL,
  'USA',
  'Double Hidraulic rising arm, 2 section telescopic mast | Max Static Hook Load 68.04 Ton | Crown Block 6 Lines Rope 1"',
  'Aktif',
  'Good',
  'On Rig BW H35KD',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '71 ton',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Load Test 71 ton based on SKPI.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- MOBENG-H35KD
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'MOBENG-H35KD',
  'Mobile Engine BW H35KD (CAT D3406)',
  (SELECT id FROM categories WHERE name = 'Mobile Engine' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW H35KD' LIMIT 1),
  'Permanent',
  'Caterpillar',
  'D3406',
  '6TB10789',
  NULL,
  NULL,
  NULL,
  'USA',
  'Power: 350 HP | Transmission: CLBT 5860-2, SN 3110090563 | Power Trans 500',
  'Aktif',
  'Good',
  'On Rig BW H35KD',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  2020,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'GOH 2020.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- MP-H35KD
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'MP-H35KD',
  'Mudpump BW H35KD (JWS-400)',
  (SELECT id FROM categories WHERE name = 'Mudpump' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW H35KD' LIMIT 1),
  'Permanent',
  NULL,
  'JWS-400',
  '1296457-1',
  NULL,
  NULL,
  NULL,
  NULL,
  'TRIPLEX PUMP, Stroke Length 7" | Engine: CAT C15, SN MCW04569, 440 HP',
  'Aktif',
  'Good',
  'On Rig BW H35KD',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- TB-H35KD
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'TB-H35KD',
  'Travelling Block BW H35KD (IDECO UIE-110)',
  (SELECT id FROM categories WHERE name = 'Travelling Block' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW H35KD' LIMIT 1),
  'Permanent',
  'IDECO',
  'UIE 110',
  'CABIB 1100061',
  NULL,
  NULL,
  NULL,
  'USA',
  '110 Ton | 3 Sheave',
  'Aktif',
  'Good',
  'On Rig BW H35KD',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- BOPDR-H35KD
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'BOPDR-H35KD',
  'BOP Double Ram BW H35KD (Shaffer)',
  (SELECT id FROM categories WHERE name = 'BOP Double Ram' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW H35KD' LIMIT 1),
  'Permanent',
  'Shaffer',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Size 7-1/16" x 5000 Psi | Type Chasovoy',
  'Aktif',
  'Good',
  'On Rig BW H35KD',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '018/COC/PTFI/XI/2016',
  'PT. FRONTKEN INDONESIA',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- ACC-H35KD
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'ACC-H35KD',
  'Accumulator BW H35KD (CAD Broussard)',
  (SELECT id FROM categories WHERE name = 'Accumulator' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW H35KD' LIMIT 1),
  'Permanent',
  'CAD Broussard',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'USA',
  'Volume 100 Gallons',
  'Aktif',
  'Good',
  'On Rig BW H35KD',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- GS-H35KD
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'GS-H35KD',
  'Genset C4.4 100Kva BW H35KD',
  (SELECT id FROM categories WHERE name = 'Genset' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW H35KD' LIMIT 1),
  'Permanent',
  'Caterpillar',
  'C4.4',
  'ECL04798',
  NULL,
  NULL,
  NULL,
  NULL,
  '100 kVA',
  'Aktif',
  'Good',
  'On Rig BW H35KD',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- TT-H35KD
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'TT-H35KD',
  'Tubing Tong BW H35KD (Wetco)',
  (SELECT id FROM categories WHERE name = 'Tubing Tong' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW H35KD' LIMIT 1),
  'Permanent',
  'Wetco',
  'HYD TUBING TONG RS',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Hydraulic Tubing Tong',
  'Aktif',
  'Good',
  'On Rig BW H35KD',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- DW-KB150A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'DW-KB150A',
  'Drawwork BW KB150.A (Cardwell KB150)',
  (SELECT id FROM categories WHERE name = 'Drawwork' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.A' LIMIT 1),
  'Permanent',
  'Cardwell',
  'KB150 / K-150',
  '105',
  1989,
  NULL,
  NULL,
  'USA',
  'Steering: Vickers V20 | Engine 300 HP | Power Drawwork 215 HP | Weight Indicator: Wagner Instrument SN W60737',
  'Aktif',
  'Good',
  'On Rig BW KB150.A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  2018,
  '586/47-26/PLO/DMT/2023',
  '2023-08-13',
  '2027-07-07',
  NULL,
  NULL,
  2012,
  'PT Petrodrill Manufactur Indonesia',
  '41 ton',
  NULL,
  NULL,
  NULL,
  'Migas',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Refurbish 2012. Service: Heavy Workover. GOH 2018.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- MAST-KB150A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'MAST-KB150A',
  'Mast BW KB150.A (29.6m)',
  (SELECT id FROM categories WHERE name = 'Mast' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.A' LIMIT 1),
  'Permanent',
  NULL,
  NULL,
  'PD-01',
  NULL,
  NULL,
  NULL,
  NULL,
  'Tubing Truss Mast 29.6 Meter | Max Static Hook Load 82 Ton 6 Line | Crown Block Wirerope 7/8"',
  'Aktif',
  'Good',
  'On Rig BW KB150.A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  2012,
  'PT Petrodrill Manufactur Indonesia',
  '41 ton',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- MP-KB150A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'MP-KB150A',
  'Mudpump BW KB150.A (OMEGA Triplex)',
  (SELECT id FROM categories WHERE name = 'Mudpump' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.A' LIMIT 1),
  'Permanent',
  'OMEGA',
  'W-500',
  '51684',
  NULL,
  NULL,
  NULL,
  NULL,
  'SINGLE ACTING TRIPLEX PUMP | Engine: CAT D3408, SN 9ER00896, 525 HP | Transmission: Allison CLT.754DB, SN 2510208479',
  'Aktif',
  'Good',
  'On Rig BW KB150.A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- TB-KB150A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'TB-KB150A',
  'Travelling Block BW KB150.A (MC Kissick 83A)',
  (SELECT id FROM categories WHERE name = 'Travelling Block' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.A' LIMIT 1),
  'Permanent',
  'MC Kissick',
  '83A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '150 Ton | Sheave Dia 30 Inch | Wire 1 inch | 4 Sheave',
  'Aktif',
  'Good',
  'On Rig BW KB150.A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- BOPA-KB150A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'BOPA-KB150A',
  'BOP Annular BW KB150.A (Hydrill GK)',
  (SELECT id FROM categories WHERE name = 'BOP Annular' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.A' LIMIT 1),
  'Permanent',
  'Hydril',
  'GK',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Size 7-1/16" x 3000 Psi',
  'Aktif',
  'Good',
  'On Rig BW KB150.A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '005/COC-RMFR/PTFI/III/19',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- ACC-KB150A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'ACC-KB150A',
  'Accumulator BW KB150.A (ABB Seatec Koomey)',
  (SELECT id FROM categories WHERE name = 'Accumulator' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.A' LIMIT 1),
  'Permanent',
  'ABB Seatec / Koomey',
  'CPCBP-4032',
  '4610',
  NULL,
  NULL,
  NULL,
  NULL,
  'Unit no. 4610',
  'Aktif',
  'Good',
  'On Rig BW KB150.A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- GS-KB150A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'GS-KB150A',
  'Genset Deutz 102KW BW KB150.A',
  (SELECT id FROM categories WHERE name = 'Genset' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.A' LIMIT 1),
  'Permanent',
  'Deutz',
  'BF04M1013EC',
  '12822784',
  NULL,
  NULL,
  NULL,
  'Germany',
  '102 kW',
  'Aktif',
  'Good',
  'On Rig BW KB150.A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- TT-KB150A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'TT-KB150A',
  'Tubing Tong BW KB150.A (Oil Country 4500)',
  (SELECT id FROM categories WHERE name = 'Tubing Tong' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.A' LIMIT 1),
  'Permanent',
  'Oil Country',
  'HYD TUBING TONG 4500',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Hydraulic Tubing Tong 4500',
  'Aktif',
  'Good',
  'On Rig BW KB150.A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- SL-KB150A
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'SL-KB150A',
  'Stand Lamp BW KB150.A',
  (SELECT id FROM categories WHERE name = 'Stand Lamp' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.A' LIMIT 1),
  'Permanent',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '3 Pcs, Class 1 Div 2, 255 Watt',
  'Aktif',
  'Good',
  'On Rig BW KB150.A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- DW-KB150B
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'DW-KB150B',
  'Drawwork BW KB150.B (Cardwell KB150)',
  (SELECT id FROM categories WHERE name = 'Drawwork' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.B' LIMIT 1),
  'Permanent',
  'Cardwell',
  'KB150 / K-150',
  '184',
  1982,
  NULL,
  NULL,
  'USA',
  'Steering: Vickers V20 | Engine 350 HP | Power Drawwork 200 HP | Weight Indicator: MD TOTO SN 81312930',
  'Aktif',
  'Good',
  'On Rig BW KB150.B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '384/47-11/PLO/DMT/2022',
  '2022-06-30',
  '2026-06-26',
  NULL,
  NULL,
  NULL,
  NULL,
  '60.17 Ton',
  NULL,
  NULL,
  NULL,
  'Migas',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Service: Light Workover.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- MAST-KB150B
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'MAST-KB150B',
  'Mast BW KB150.B (29.6m)',
  (SELECT id FROM categories WHERE name = 'Mast' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.B' LIMIT 1),
  'Permanent',
  NULL,
  NULL,
  '184',
  NULL,
  NULL,
  NULL,
  NULL,
  'Tubing Truss Mast 29.6 mtrs | Crown Block 6 Lines Rope 7/8"',
  'Aktif',
  'Good',
  'On Rig BW KB150.B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '60.17 Ton',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- MP-KB150B
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'MP-KB150B',
  'Mudpump BW KB150.B (Gardner Denver)',
  (SELECT id FROM categories WHERE name = 'Mudpump' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.B' LIMIT 1),
  'Permanent',
  'Gardner Denver',
  'TGHP-200',
  '14942',
  NULL,
  NULL,
  NULL,
  NULL,
  '535 GPM, Liner 7", 286 RPM | Engine: CAT D3406, SN 3ZJ061815 | Transmission: Allison HT.740, SN 2510051777',
  'Aktif',
  'Good',
  'On Rig BW KB150.B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Working Pressure 535 GPM.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- TB-KB150B
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'TB-KB150B',
  'Travelling Block BW KB150.B (MC Kissick 83A)',
  (SELECT id FROM categories WHERE name = 'Travelling Block' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.B' LIMIT 1),
  'Permanent',
  'MC Kissick',
  '83A',
  '0254134',
  NULL,
  NULL,
  NULL,
  NULL,
  '3 Sheave',
  'Aktif',
  'Good',
  'On Rig BW KB150.B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- BOPA-KB150B
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'BOPA-KB150B',
  'BOP Annular BW KB150.B (Shaffer)',
  (SELECT id FROM categories WHERE name = 'BOP Annular' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.B' LIMIT 1),
  'Permanent',
  'Shaffer',
  'Chasovoy',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Size 7-1/16" x 3000 Psi',
  'Aktif',
  'Good',
  'On Rig BW KB150.B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- ACC-KB150B
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'ACC-KB150B',
  'Accumulator BW KB150.B',
  (SELECT id FROM categories WHERE name = 'Accumulator' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.B' LIMIT 1),
  'Permanent',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Verifikasi SKPP Bejana Tekan',
  'Aktif',
  'Fair',
  'On Rig BW KB150.B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2015-02-05',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'SKPP Bejana Tekan until 05 Feb 2015 — perlu di-cek status terbaru.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- GS-KB150B
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'GS-KB150B',
  'Genset Deutz 74.9KW BW KB150.B',
  (SELECT id FROM categories WHERE name = 'Genset' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.B' LIMIT 1),
  'Permanent',
  'Deutz',
  'BF4M2012C',
  '60386305',
  NULL,
  NULL,
  NULL,
  'Germany',
  '74.9 kW',
  'Aktif',
  'Good',
  'On Rig BW KB150.B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- TT-KB150B
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'TT-KB150B',
  'Tubing Tong BW KB150.B (BJ Cavins)',
  (SELECT id FROM categories WHERE name = 'Tubing Tong' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.B' LIMIT 1),
  'Permanent',
  'BJ Cavins',
  'HYD TUBING TONG RS',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Hydraulic Tubing Tong',
  'Aktif',
  'Good',
  'On Rig BW KB150.B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- SL-KB150B
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'SL-KB150B',
  'Stand Lamp BW KB150.B',
  (SELECT id FROM categories WHERE name = 'Stand Lamp' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.B' LIMIT 1),
  'Permanent',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '3 Pcs, Class 1 Div 2, 255 Watt',
  'Aktif',
  'Good',
  'On Rig BW KB150.B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- DW-KB150C
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'DW-KB150C',
  'Drawwork BW KB150.C (Cardwell KB150)',
  (SELECT id FROM categories WHERE name = 'Drawwork' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.C' LIMIT 1),
  'Permanent',
  'Cardwell',
  'KB150 / K-150',
  '197',
  1989,
  NULL,
  NULL,
  'USA',
  'Steering: Vickers V20 | Engine 300 HP | Power Drawwork 200 HP | Weight Indicator: SN 110217 Type 6A93-0200-46 MD Totco',
  'Aktif',
  'Good',
  'On Rig BW KB150.C',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  2017,
  '538/47-2/PLO/DMT/2018',
  '2022-11-27',
  '2026-10-26',
  NULL,
  NULL,
  2016,
  'PT Petrodrill Manufactur Indonesia',
  '34.02 ton',
  NULL,
  NULL,
  NULL,
  'Migas',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Refurbish 2016. Service: Heavy Workover. GOH 2017.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- MAST-KB150C
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'MAST-KB150C',
  'Mast BW KB150.C (21.03m)',
  (SELECT id FROM categories WHERE name = 'Mast' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.C' LIMIT 1),
  'Permanent',
  NULL,
  NULL,
  'PD30-M075-069',
  NULL,
  NULL,
  NULL,
  NULL,
  'Tubing Truss Mast 21.03 mtrs | Crown Block 5 Sheave Wirerope 7/8"',
  'Aktif',
  'Good',
  'On Rig BW KB150.C',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  2016,
  'PT Petrodrill Manufactur Indonesia',
  '34.02 ton',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- MP-KB150C
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'MP-KB150C',
  'Mudpump BW KB150.C (SPM Triplex)',
  (SELECT id FROM categories WHERE name = 'Mudpump' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.C' LIMIT 1),
  'Permanent',
  'SPM',
  'TWS600STD',
  'F0904-2404',
  NULL,
  NULL,
  NULL,
  NULL,
  'SINGLE ACTING TRIPLEX PUMP | Engine: CAT D.3406, SN 3ER08763 | Transmission: Allison S5610DR, SN 3110049960',
  'Aktif',
  'Good',
  'On Rig BW KB150.C',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- TB-KB150C
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'TB-KB150C',
  'Travelling Block BW KB150.C (MC Kissick 65 Ton)',
  (SELECT id FROM categories WHERE name = 'Travelling Block' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.C' LIMIT 1),
  'Permanent',
  'MC Kissick',
  NULL,
  '41262947',
  NULL,
  NULL,
  NULL,
  NULL,
  '65 Ton | Sheave Dia 24 Inch | Wire 7/8 inch | 3 Sheave',
  'Aktif',
  'Good',
  'On Rig BW KB150.C',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- BOPDR-KB150C
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'BOPDR-KB150C',
  'BOP Double Ram BW KB150.C',
  (SELECT id FROM categories WHERE name = 'BOP Double Ram' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.C' LIMIT 1),
  'Permanent',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Size 7-1/16" x 3000 Psi',
  'Aktif',
  'Good',
  'On Rig BW KB150.C',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '011/COC/PTFI/IV/16',
  'PT. Frontken Indonesia',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- BOPR-KB150C
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'BOPR-KB150C',
  'BOP Pipe Ram BW KB150.C (Shaffer)',
  (SELECT id FROM categories WHERE name = 'BOP Single Ram' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.C' LIMIT 1),
  'Permanent',
  'Shaffer',
  NULL,
  'A2112',
  NULL,
  NULL,
  NULL,
  NULL,
  'Size 7-1/16" x 3000 PSI DOUBLE RAM',
  'Aktif',
  'Good',
  'On Rig BW KB150.C',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '027/COC/PTFI/X/15',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2015-10-16',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'COC Pipe Ram BOP.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- ACC-KB150C
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'ACC-KB150C',
  'Accumulator BW KB150.C (ABB Seatec)',
  (SELECT id FROM categories WHERE name = 'Accumulator' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.C' LIMIT 1),
  'Permanent',
  'ABB Seatec',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2 Botol',
  'Aktif',
  'Good',
  'On Rig BW KB150.C',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- GS-KB150C
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'GS-KB150C',
  'Genset Deutz BW KB150.C',
  (SELECT id FROM categories WHERE name = 'Genset' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.C' LIMIT 1),
  'Permanent',
  'Deutz',
  '1013',
  '102514',
  NULL,
  NULL,
  NULL,
  'Germany',
  'Model 1013',
  'Aktif',
  'Good',
  'On Rig BW KB150.C',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- TT-KB150C
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'TT-KB150C',
  'Tubing Tong BW KB150.C (Oil Country)',
  (SELECT id FROM categories WHERE name = 'Tubing Tong' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.C' LIMIT 1),
  'Permanent',
  'Oil Country',
  'HYD TUBING TONG 4500',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Hydraulic Tubing Tong 4500',
  'Aktif',
  'Good',
  'On Rig BW KB150.C',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT (tag_number) DO NOTHING;

-- SL-KB150C
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'SL-KB150C',
  'Stand Lamp BW KB150.C — TIDAK ADA',
  (SELECT id FROM categories WHERE name = 'Stand Lamp' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'BW KB150.C' LIMIT 1),
  'Permanent',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'STATUS: Tidak ada (perlu pengadaan)',
  'Down',
  'Poor',
  'On Rig BW KB150.C',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Catatan dari data lama: Tidak ada Stand Lamp di rig ini.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- MP-BACKUP-01
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'MP-BACKUP-01',
  'Mudpump Backup Shared Pool',
  (SELECT id FROM categories WHERE name = 'Mudpump' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'Independent' LIMIT 1),
  'Mobile-Backup',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Mudpump cadangan, bisa dipake ke semua rig',
  'Standby',
  'Good',
  'Yard Base Camp',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'MOBILE-BACKUP — Lengkapi data: brand, model, SN, dll.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- MP-ACID-01
INSERT INTO equipment (tag_number, nama_equipment, kategori_id, assigned_unit_id, tipe_kepemilikan, brand, model, serial_number, tahun_pembuatan, tahun_commissioning, year_used, country_of_origin, spek_khusus, status_operasi, kondisi_fisik, lokasi_fisik, running_hours, last_maintenance_date, last_maintenance_type, next_maintenance_date, maintenance_interval, pic_mechanic, goh_year, nomor_skpi, skpi_start_date, skpi_end_date, coc_number, arf_lembaga, refurbish_year, refurbish_by, load_test_result, nomor_sertifikat_lain, tgl_terbit_sertifikat, tgl_expired_sertifikat, lembaga_penerbit, tgl_pembelian, harga_perolehan, nomor_po_invoice, vendor_supplier, cost_center, pressure_test_date, pressure_test_result, remarks)
VALUES (
  'MP-ACID-01',
  'MUDPUMP Acid',
  (SELECT id FROM categories WHERE name = 'MUDPUMP Acid' LIMIT 1),
  (SELECT id FROM parent_units WHERE name = 'Independent' LIMIT 1),
  'Permanent',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Mudpump khusus untuk acid stimulation',
  'Standby',
  'Good',
  'Yard Base Camp',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'FIXED di Independent. Lengkapi data spek.'
)
ON CONFLICT (tag_number) DO NOTHING;

-- Verifikasi: jumlah equipment yang masuk
SELECT COUNT(*) AS total_equipment FROM equipment;
-- Ekspektasi: minimum 49 baris (atau lebih kalau sudah ada data sebelumnya)

COMMIT;